services:
  mlflow-server:
    image: ghcr.io/mlflow/mlflow:v2.7.1
    container_name: mlflow_local
    ports:
      - "5001:5001"
    # This command starts the server and saves data to a local 'mlflow.db' file
    command: mlflow server --backend-store-uri sqlite:///mlflow/mlflow.db --default-artifact-root mlflow-artifacts:/ --host 0.0.0.0 --port 5001 --serve-artifacts --artifacts-destination /mlflow/artifacts
    volumes:
      - ./mlflow_data:/mlflow
  
  prefect-server:
    image: prefecthq/prefect:2-latest
    container_name: prefect_local
    ports:
      - "4200:4200"
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
    command: prefect server start
    volumes:
      - ./prefect_data:/root/.prefect