"""Comparison report generation for model ranking."""

from datetime import datetime
from typing import List, Optional

from ..evaluation.embedding_evaluator import EvaluationResult
from .model_ranker import RankedModel


class ComparisonReportGenerator:
    """Generates comparison reports for evaluated models."""

    def __init__(self, min_precision: float = 0.80):
        """
        Initialize report generator.

        Args:
            min_precision: Precision constraint used in evaluation
        """
        self.min_precision = min_precision

    def generate_markdown_report(
        self,
        ranked_models: List[RankedModel],
        all_results: Optional[List[EvaluationResult]] = None,
    ) -> str:
        """
        Generate a markdown comparison report.

        Args:
            ranked_models: Ranked models (top-N selected)
            all_results: All evaluation results (for full comparison)

        Returns:
            Markdown formatted report
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        report = f"""# Model Evaluation Report

**Generated:** {timestamp}
**Precision Constraint:** >= {self.min_precision:.2f}
**Models Selected:** {len(ranked_models)}

---

## Selected Models for LoRA Training

| Rank | Model | F1 Score | Precision | Recall | Threshold | Latency |
|------|-------|----------|-----------|--------|-----------|---------|
"""
        for model in ranked_models:
            report += (
                f"| {model.rank} | {model.model_name} | "
                f"{model.f1_score:.4f} | {model.precision:.4f} | "
                f"{model.recall:.4f} | {model.optimal_threshold:.3f} | "
                f"{model.latency_ms_per_pair:.2f}ms |\n"
            )

        report += f"""
---

## Top Model Details

**Selected Model:** {ranked_models[0].model_name if ranked_models else "N/A"}
"""

        if ranked_models:
            top = ranked_models[0]
            report += f"""
- **Model ID:** `{top.model_id}`
- **Dimension:** {top.dimension}
- **Category:** {top.category}
- **F1 Score:** {top.f1_score:.4f}
- **Precision:** {top.precision:.4f}
- **Recall:** {top.recall:.4f}
- **Optimal Threshold:** {top.optimal_threshold:.3f}
- **Latency:** {top.latency_ms_per_pair:.2f}ms per pair
"""

        # Add full comparison if available
        if all_results:
            report += self._generate_full_comparison(all_results)

        report += """
---

## Next Steps

1. LoRA fine-tuning will be performed on the selected models
2. Fine-tuned models will be registered in MLFlow Model Registry
3. Best performing LoRA adapter will be promoted to staging

---

*This report was automatically generated by the embedding evaluation pipeline.*
"""

        return report

    def _generate_full_comparison(
        self,
        all_results: List[EvaluationResult],
    ) -> str:
        """Generate full comparison section for all evaluated models."""
        # Separate successful and failed
        successful = [r for r in all_results if r.success]
        failed = [r for r in all_results if not r.success]

        # Sort successful by F1 score
        successful.sort(key=lambda r: r.f1_score, reverse=True)

        report = """
---

## Full Model Comparison

### Successful Evaluations

| Model | Category | F1 Score | Precision | Recall | Threshold | Constraint Met |
|-------|----------|----------|-----------|--------|-----------|----------------|
"""
        for r in successful:
            constraint_met = "Yes" if r.meets_precision_constraint else "No"
            report += (
                f"| {r.model_name} | {r.category} | "
                f"{r.f1_score:.4f} | {r.precision:.4f} | "
                f"{r.recall:.4f} | {r.optimal_threshold or 0:.3f} | "
                f"{constraint_met} |\n"
            )

        # Add failed models
        if failed:
            report += """
### Failed Evaluations

| Model | Error |
|-------|-------|
"""
            for r in failed:
                error = (r.error or "Unknown error")[:50]
                report += f"| {r.model_name} | {error} |\n"

        # Add statistics
        report += f"""
### Statistics

- **Total Models Evaluated:** {len(all_results)}
- **Successful:** {len(successful)}
- **Failed:** {len(failed)}
- **Meeting Precision Constraint:** {sum(1 for r in successful if r.meets_precision_constraint)}
"""

        if successful:
            report += f"""
- **Best F1 Score:** {successful[0].f1_score:.4f} ({successful[0].model_name})
- **Average F1 Score:** {sum(r.f1_score for r in successful) / len(successful):.4f}
"""

        return report

    def generate_csv_report(
        self,
        ranked_models: List[RankedModel],
    ) -> str:
        """
        Generate CSV format report for data analysis.

        Args:
            ranked_models: Ranked models

        Returns:
            CSV formatted string
        """
        headers = [
            "rank",
            "model_key",
            "model_name",
            "model_id",
            "dimension",
            "category",
            "f1_score",
            "precision",
            "recall",
            "accuracy",
            "optimal_threshold",
            "latency_ms_per_pair",
        ]

        rows = [",".join(headers)]

        for model in ranked_models:
            row = [
                str(model.rank),
                model.model_key,
                model.model_name,
                model.model_id,
                str(model.dimension),
                model.category,
                f"{model.f1_score:.4f}",
                f"{model.precision:.4f}",
                f"{model.recall:.4f}",
                f"{model.accuracy:.4f}",
                f"{model.optimal_threshold:.3f}",
                f"{model.latency_ms_per_pair:.2f}",
            ]
            rows.append(",".join(row))

        return "\n".join(rows)

    def generate_json_report(
        self,
        ranked_models: List[RankedModel],
    ) -> dict:
        """
        Generate JSON format report.

        Args:
            ranked_models: Ranked models

        Returns:
            Report dictionary
        """
        return {
            "timestamp": datetime.now().isoformat(),
            "min_precision_constraint": self.min_precision,
            "num_selected": len(ranked_models),
            "models": [model.to_dict() for model in ranked_models],
            "best_model": ranked_models[0].to_dict() if ranked_models else None,
        }
